import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // lib/gallery.ts reads public/images at BUILD time, which made Next trace the
  // whole public/ tree (images + PDFs) into every serverless function that
  // touches it — 364MB, over Vercel's 250MB limit, so deploys failed outright.
  // Static assets are served by the CDN, never from the function bundle, and
  // every gallery consumer is prerendered, so excluding this is safe.
  outputFileTracingExcludes: {
    "**/*": ["public/**"],
  },
  async redirects() {
    return [
      // Products
      { source: "/trafficpatternsxd", destination: "/products/trafficpatterns-xd", permanent: true },
      { source: "/trafficpatterns", destination: "/products/trafficpatterns", permanent: true },
      { source: "/streetprint", destination: "/products/streetprint", permanent: true },
      { source: "/streetbond", destination: "/products/streetbond", permanent: true },
      { source: "/streetbondsr", destination: "/products/streetbond", permanent: true },
      { source: "/mmax-2", destination: "/products/mmax", permanent: true },
      { source: "/decomark", destination: "/products/decomark", permanent: true },
      { source: "/duratherm-2", destination: "/products/duratherm", permanent: true },
      { source: "/durashield", destination: "/products/durashield", permanent: true },
      { source: "/premark", destination: "/products/premark", permanent: true },
      { source: "/airmark", destination: "/products", permanent: true },
      // Applications
      { source: "/crosswalks", destination: "/applications/crosswalks", permanent: true },
      { source: "/bike-bus-lanes", destination: "/applications/bike-lanes", permanent: true },
      { source: "/parking-lots", destination: "/applications/parking-lots", permanent: true },
      { source: "/commercial-parking-lot-solutions", destination: "/applications/parking-lots", permanent: true },
      { source: "/commercial-parking-lot-surfaces", destination: "/applications/parking-lots", permanent: true },
      { source: "/parks-paths", destination: "/applications/parks-paths", permanent: true },
      { source: "/public-art", destination: "/applications/public-art", permanent: true },
      { source: "/community-branding", destination: "/applications/branding-wayfinding", permanent: true },
      { source: "/regulatory-markings", destination: "/applications", permanent: true },
      { source: "/air-ports", destination: "/applications", permanent: true },
      { source: "/residential-driveways", destination: "/driveways", permanent: true },
      { source: "/private-driveways", destination: "/driveways", permanent: true },
      { source: "/townhomes", destination: "/driveways", permanent: true },
      { source: "/applications/private-driveways", destination: "/driveways", permanent: true },
      { source: "/leed-urban-heat-island", destination: "/applications", permanent: true },
      { source: "/splash-pads", destination: "/applications/parks-paths", permanent: true },
      { source: "/applications/driveways", destination: "/driveways", permanent: true },
      { source: "/decorative-streetscape-solutions", destination: "/applications/crosswalks", permanent: true },
      // Blog post redirects
      { source: "/keeping-pedestrians-safe-and-operation-budgets-low", destination: "/blog", permanent: true },
      { source: "/pedestrian-safety-solutions", destination: "/blog", permanent: true },
      { source: "/vancouver-decorative-crosswalk-design", destination: "/blog", permanent: true },
      { source: "/enhancing-multimodal-connectivity-in-york-region-toronto", destination: "/blog", permanent: true },
      { source: "/case-study-branded-crosswalks-and-pedestrian-safety-in-vancouver-richmond", destination: "/blog", permanent: true },
      { source: "/decorative-asphalt-for-high-traffic-areas", destination: "/blog", permanent: true },
      { source: "/veterans-crosswalk-kitchener-trafficpatterns", destination: "/blog", permanent: true },
      { source: "/trafficpatternsdx-mmax-durable-transit-lanes-crossings", destination: "/blog", permanent: true },
      { source: "/trafficpatterns-crosswalks-white-rock-langley", destination: "/blog", permanent: true },
      { source: "/decorative-hardscape-solutions-grey-is-the-new-black", destination: "/blog", permanent: true },
      { source: "/decorative-paving-solutions", destination: "/blog", permanent: true },
      { source: "/trafficpatternsxd-urban-design-solutions", destination: "/blog", permanent: true },
      { source: "/streetbondsr-solar-reflective-coatings", destination: "/blog", permanent: true },
      { source: "/new-traffic-pattern-crosswalk-upgrade-for-tsain-ko-centre-2", destination: "/blog/pictograph-crosswalk-sechelt", permanent: true },
      { source: "/strengthening-cycling-and-transit-integration-with-long-lasting-surface-solutions", destination: "/blog", permanent: true },
      { source: "/enhancing-safety-and-durability-for-high-traffic-transit-stations", destination: "/blog", permanent: true },
      { source: "/extending-transit-lane-lifespan", destination: "/blog", permanent: true },
      { source: "/transportation-infrastructure-guide", destination: "/blog", permanent: true },
      { source: "/playgrounds-recreation-case-studies", destination: "/blog", permanent: true },
      { source: "/educational-facilities-case-study", destination: "/blog", permanent: true },
      { source: "/community-spaces-case-study", destination: "/blog", permanent: true },
      { source: "/community-branding-case-study", destination: "/blog", permanent: true },
      { source: "/commercial-applications-case-study", destination: "/blog", permanent: true },
      { source: "/municipalities-case-studies", destination: "/blog", permanent: true },
      { source: "/stamped-asphalt-vs-stamped-concrete", destination: "/blog/stamped-asphalt-vs-concrete-driveways-bc", permanent: true },
      // White papers
      { source: "/white-paper-transportation-and-urban-design", destination: "/blog", permanent: true },
      { source: "/white-paper-surface-solutions-for-resilient-transit-infrastructure", destination: "/blog", permanent: true },
      // Blog posts & project profiles (2020–2022)
      { source: "/surface-system-solutions-for-school-playgrounds", destination: "/blog", permanent: true },
      { source: "/decorative-asphalt-for-communities", destination: "/blog", permanent: true },
      { source: "/asphalt-coatings-for-parks-and-plazas", destination: "/blog", permanent: true },
      { source: "/streetbondsr-for-cooler-asphalt-surfaces", destination: "/blog", permanent: true },
      { source: "/enhancing-transit-hubs-in-the-gta-and-metro-vancouver", destination: "/blog", permanent: true },
      { source: "/new-traffic-pattern-crosswalk-upgrade-for-tsain-ko-centre", destination: "/blog/traffic-pattern-crosswalk-upgrade-for-tsain-ko-centre", permanent: true },
      { source: "/decorative-asphalt-crosswalks", destination: "/blog", permanent: true },
      { source: "/roadway-accents-natures-walk", destination: "/blog/townhouse-driveway-natures-walk", permanent: true },
      { source: "/every-child-matters-decorative-asphalt-crosswalk", destination: "/blog/every-child-matters-new-westminster", permanent: true },
      { source: "/stamped-asphalt-parking-lot", destination: "/blog", permanent: true },
      { source: "/terry-fox-decorative-asphalt-plaza-coquitlam", destination: "/blog/decorative-asphalt-plaza", permanent: true },
      { source: "/decorative-crosswalk-and-meridian", destination: "/blog", permanent: true },
      { source: "/the-laneway-project", destination: "/blog", permanent: true },
      { source: "/parc-riviera-mews-streetbond-asphalt-walkway", destination: "/blog/parc-riviera-mews-streetbond-asphalt-walkway", permanent: true },
      { source: "/decorative-asphalt-for-rutland-centennial-park-kelowna", destination: "/blog/decorative-asphalt-for-rutland-centennial-park-kelowna", permanent: true },
      { source: "/societe-de-transport-du-saguenay", destination: "/blog", permanent: true },
      { source: "/bikeway-intersection", destination: "/blog", permanent: true },
      { source: "/decorative-asphalt-renewal", destination: "/blog", permanent: true },
      { source: "/asphalt-coatings-for-playgrounds", destination: "/blog", permanent: true },
      { source: "/west-vancouver-rainbow-crosswalk", destination: "/blog/west-vancouver-rainbow-crosswalk", permanent: true },
      { source: "/ackerys-alley-decorative-asphalt-orpheum-theatre-laneway", destination: "/blog", permanent: true },
      { source: "/decorative-paving-stamped-asphalt-after-2-years-wear", destination: "/blog/decorative-paving-stamped-asphalt", permanent: true },
      { source: "/ralphs-farm-market-decorative-asphalt-parking-lot", destination: "/blog/ralphs-farm-market-decorative-parking-lot", permanent: true },
      { source: "/reunion-murrayville-schoolhouse-decorative-asphalt-sidewalk", destination: "/blog/decorative-asphalt-sidewalk-for-langley-housing-development", permanent: true },
      { source: "/decorative-crosswalk_richmond-brighouse", destination: "/blog/richmond-brighouse-translink", permanent: true },
      { source: "/decorative-asphalt-path", destination: "/blog/bowen-island-stamped-asphalt-walkway", permanent: true },
      { source: "/ubc-musqueam-crosswalk", destination: "/blog/ubc-musqueam-crosswalk", permanent: true },
      { source: "/white-rock-pier-decoraive-crosswalk", destination: "/blog/white-rock-crosswalk", permanent: true },
      { source: "/squamish-nation-rainbow-crosswalk", destination: "/blog/rainbow-crosswalk-squamish", permanent: true },
      { source: "/melfort-saskatchewan-waterpark-splash-pad", destination: "/blog", permanent: true },
      { source: "/victoria-harbor-decorative-asphalt-walkway", destination: "/blog/victoria-harbour-walkway", permanent: true },
      { source: "/sports-court-asphalt-paving", destination: "/blog/sport-court-asphalt-paving", permanent: true },
      { source: "/rainbow-crosswalk-sechelt", destination: "/blog", permanent: true },
      { source: "/white-rock-stamped-asphalt-pathway", destination: "/blog", permanent: true },
      { source: "/checkerboard-decorative-asphalt-crosswalk", destination: "/blog/checkerboard-crosswalks-coquitlam", permanent: true },
      { source: "/first-nations-decorative-crosswalk-design-granville-street", destination: "/blog/first-nations-crosswalk-design-granville-street", permanent: true },
      { source: "/lickman-interchange-decorative-asphalt-roundabout", destination: "/blog/lickman-interchange", permanent: true },
      { source: "/stamped-asphalt-streetscapes-viva-next", destination: "/blog", permanent: true },
      { source: "/decorative-paving-for-townhomes-canada", destination: "/blog", permanent: true },
      { source: "/decorative-paving-public-art", destination: "/blog/joyce-skytrain-art-installation", permanent: true },
      { source: "/decorative-crosswalk-commercial-drive", destination: "/blog", permanent: true },
      { source: "/pedestrian-channelization-public-spaces", destination: "/blog", permanent: true },
      { source: "/decorative-paving-labyrinth-bc-childrens-hospital", destination: "/blog", permanent: true },
      { source: "/best-crosswalks-canada", destination: "/blog", permanent: true },
      { source: "/durable-pavement-coatings-ideal-for-waterparks", destination: "/blog", permanent: true },
      { source: "/complete-streets-new-westminster", destination: "/blog", permanent: true },
      { source: "/community-branding-horizontal-wayfinding-for-vancouvers-spirit-trail", destination: "/blog", permanent: true },
      { source: "/performance-crosswalks-for-asphalt-and-concrete", destination: "/blog", permanent: true },
      { source: "/imprinted-asphalt-crosswalks-for-york-transit-corridor", destination: "/blog", permanent: true },
      { source: "/residential-decorative-paving", destination: "/blog", permanent: true },
      { source: "/laneway-revitalization", destination: "/blog", permanent: true },
      { source: "/residential-decorative-driveways", destination: "/blog/residential-driveways-bc", permanent: true },
      { source: "/decorative-paving-for-playgrounds", destination: "/blog", permanent: true },
      { source: "/parking-lot-wayfinding", destination: "/blog", permanent: true },
      { source: "/durable-coatings-for-asphalt", destination: "/blog", permanent: true },
      { source: "/stamped-asphalt-decorative-crosswalks", destination: "/blog", permanent: true },
      { source: "/enhanced-parking-lot-surfaces", destination: "/blog", permanent: true },
      // Footer/nav link variants
      { source: "/traffic-patterns", destination: "/products/trafficpatterns", permanent: true },
      // Other pages
      { source: "/vapor-blasting", destination: "/services/vapor-blasting", permanent: true },
      { source: "/case-studies", destination: "/projects", permanent: true },
      { source: "/featured-projects", destination: "/projects", permanent: true },
      { source: "/documentation", destination: "/resources", permanent: true },
      { source: "/about-us", destination: "/about", permanent: true },
      { source: "/contact-us", destination: "/contact", permanent: true },
    ];
  },
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "images.unsplash.com" },
      { protocol: "https", hostname: "plus.unsplash.com" },
      { protocol: "https", hostname: "squareonepaving.com" },
      { protocol: "https", hostname: "www.squareonepaving.com" },
    ],
  },
};

export default nextConfig;
