import manifest from "./doc-previews.json"

/**
 * Pre-rendered page-one previews for the document library — generated by
 * scripts/doc-previews.mjs into public/docs-previews/ and indexed here by
 * the document's href. Nothing renders PDFs in the browser or at build
 * time: a document with no entry simply has no preview, and the UI falls
 * back to its type tile.
 */
export interface DocPreview {
  /** 1000px-wide WebP of page one — the in-page preview. */
  preview: string
  /** 320px-wide WebP of page one — the row thumbnail. */
  thumb: string
  w: number
  h: number
}

const PREVIEWS: Record<string, DocPreview> = manifest

export function previewFor(href: string): DocPreview | undefined {
  return PREVIEWS[href]
}

export const previewCount = Object.keys(PREVIEWS).length
