/**
 * The one public origin of the site. Every canonical, sitemap entry, JSON-LD
 * @id and OG URL derives from here — nothing else may hard-code the host.
 *
 * Until 11 Sept 2026 the codebase carried both: 34 references to
 * squareonepaving.ca (canonicals, schema, OG) and 2 to squareonepaving.com
 * (sitemap, robots). A sitemap on one host listing pages whose canonicals
 * point at another is the kind of SEO mistake that is expensive to undo.
 *
 * The default is .com — the domain the client's live site, email signatures
 * and HUB's links all use. Override with NEXT_PUBLIC_SITE_URL in Vercel if
 * that is ever wrong; do not edit this file to change hosts.
 */
export const SITE_URL: string = (process.env.NEXT_PUBLIC_SITE_URL ?? "https://squareonepaving.com").replace(/\/+$/, "")

/** Absolute URL for a site path. `abs("/products")` → "https://squareonepaving.com/products". */
export function abs(path = ""): string {
  if (!path || path === "/") return SITE_URL
  return `${SITE_URL}${path.startsWith("/") ? "" : "/"}${path}`
}
