import type { WorkPhoto } from "@/lib/work"

/**
 * Captions for the 2026 photo library in public/images/applications/<slug>/.
 *
 * Keyed by web path. Every value comes from the curation manifest (source
 * folder, city and system as Square One filed them) — nothing is parsed from
 * the filename and nothing is guessed. lib/work.ts skips any file in those
 * folders without an entry here.
 *
 * Private homes carry the city only, never a street or an address.
 */
export type WorkCaption = Pick<WorkPhoto, "subject" | "place" | "systems">

export const WORK_CAPTIONS: Record<string, WorkCaption> = {
  // crosswalks
  "/images/applications/crosswalks/delta-gateway-casino-brick-crossing-trafficpatterns-01.jpg": { subject: "Gateway Casino brick crossing", place: "Delta", systems: ["TrafficPatterns"] },
  "/images/applications/crosswalks/delta-gateway-casino-crossing-detail-trafficpatterns-01.jpg": { subject: "Gateway Casino crossing detail", place: "Delta", systems: ["TrafficPatterns"] },
  "/images/applications/crosswalks/delta-gateway-casino-rumble-strips-and-crossing-trafficpatterns-01.jpg": { subject: "Gateway Casino rumble strips and crossing", place: "Delta", systems: ["TrafficPatterns"] },
  "/images/applications/crosswalks/langley-railways-crossing-at-the-heritage-block-trafficpatternsxd-01.jpg": { subject: "Railways crossing at the heritage block", place: "Langley", systems: ["TrafficPatternsXD"] },
  "/images/applications/crosswalks/langley-railways-crossing-crew-on-site-trafficpatternsxd-01.jpg": { subject: "Railways crossing, crew on site", place: "Langley", systems: ["TrafficPatternsXD"] },
  "/images/applications/crosswalks/new-westminster-agnes-greenway-crossing-trafficpatternsxd-01.jpg": { subject: "Agnes Greenway crossing", place: "New Westminster", systems: ["TrafficPatternsXD"] },
  "/images/applications/crosswalks/new-westminster-agnes-greenway-crossing-with-bike-lane-trafficpatternsxd-01.jpg": { subject: "Agnes Greenway crossing with bike lane", place: "New Westminster", systems: ["TrafficPatternsXD"] },
  "/images/applications/crosswalks/new-westminster-large-format-tile-crossing-streetprint-01.jpg": { subject: "Large-format tile crossing", place: "New Westminster", systems: ["StreetPrint"] },
  "/images/applications/crosswalks/north-vancouver-townhome-street-crossing-trafficpatternsxd-01.jpg": { subject: "Townhome street crossing", place: "North Vancouver", systems: ["TrafficPatternsXD"] },
  "/images/applications/crosswalks/north-vancouver-townhome-street-crossing-wide-trafficpatternsxd-01.jpg": { subject: "Townhome street crossing, wide", place: "North Vancouver", systems: ["TrafficPatternsXD"] },
  "/images/applications/crosswalks/richmond-crossing-between-towers-trafficpatternsxd-01.jpg": { subject: "Crossing between towers", place: "Richmond", systems: ["TrafficPatternsXD"] },
  "/images/applications/crosswalks/richmond-crossing-on-the-arterial-trafficpatternsxd-01.jpg": { subject: "Crossing on the arterial", place: "Richmond", systems: ["TrafficPatternsXD"] },
  "/images/applications/crosswalks/richmond-crossing-with-tactile-edge-trafficpatternsxd-01.jpg": { subject: "Crossing with tactile edge", place: "Richmond", systems: ["TrafficPatternsXD"] },
  "/images/applications/crosswalks/white-rock-shoreline-crossing-from-the-promenade-trafficpatternsxd-01.jpg": { subject: "Shoreline crossing from the promenade", place: "White Rock", systems: ["TrafficPatternsXD"] },
  "/images/applications/crosswalks/white-rock-shoreline-crossing-trafficpatternsxd-01.jpg": { subject: "Shoreline crossing", place: "White Rock", systems: ["TrafficPatternsXD"] },
  // streetscapes
  "/images/applications/streetscapes/coquitlam-glen-and-pine-plaza-trafficpatternsxd-01.jpg": { subject: "Glen and Pine plaza", place: "Coquitlam", systems: ["TrafficPatternsXD"] },
  "/images/applications/streetscapes/squamish-strata-laneway-streetbond-01.jpg": { subject: "Strata laneway", place: "Squamish", systems: ["StreetBond"] },
  "/images/applications/streetscapes/squamish-strata-laneway-wide-streetbond-01.jpg": { subject: "Strata laneway, wide", place: "Squamish", systems: ["StreetBond"] },
  "/images/applications/streetscapes/surrey-32nd-avenue-median-streetprint-01.jpg": { subject: "32nd Avenue median", place: "Surrey", systems: ["StreetPrint"] },
  "/images/applications/streetscapes/victoria-heritage-building-forecourt-streetprint-01.jpg": { subject: "Heritage building forecourt", place: "Victoria", systems: ["StreetPrint"] },
  "/images/applications/streetscapes/victoria-town-centre-crossing-streetprint-01.jpg": { subject: "Town centre crossing", place: "Victoria", systems: ["StreetPrint"] },
  "/images/applications/streetscapes/victoria-town-centre-paving-streetprint-01.jpg": { subject: "Town centre paving", place: "Victoria", systems: ["StreetPrint"] },
  "/images/applications/streetscapes/victoria-town-centre-plaza-streetprint-01.jpg": { subject: "Town centre plaza", place: "Victoria", systems: ["StreetPrint"] },
  "/images/applications/streetscapes/victoria-vic-high-approach-streetprint-01.jpg": { subject: "Vic High approach", place: "Victoria", systems: ["StreetPrint"] },
  "/images/applications/streetscapes/victoria-vic-high-forecourt-streetprint-01.jpg": { subject: "Vic High forecourt", place: "Victoria", systems: ["StreetPrint"] },
  // roundabouts
  "/images/applications/roundabouts/abbotsford-roundabout-apron-streetprint-01.jpg": { subject: "Roundabout apron", place: "Abbotsford", systems: ["StreetPrint"] },
  "/images/applications/roundabouts/abbotsford-roundabout-wide-streetprint-01.jpg": { subject: "Roundabout, wide", place: "Abbotsford", systems: ["StreetPrint"] },
  "/images/applications/roundabouts/chilliwack-circular-turnaround-streetprint-01.jpg": { subject: "Circular turnaround", place: "Chilliwack", systems: ["StreetPrint"] },
  "/images/applications/roundabouts/maple-ridge-roundabout-centre-streetprint-01.jpg": { subject: "Roundabout centre", place: "Maple Ridge", systems: ["StreetPrint"] },
  "/images/applications/roundabouts/maple-ridge-traffic-island-streetprint-01.jpg": { subject: "Traffic island", place: "Maple Ridge", systems: ["StreetPrint"] },
  // parking-lots
  "/images/applications/parking-lots/mission-parking-bays-and-lot-streetprint-01.jpg": { subject: "Parking bays and lot", place: "Mission", systems: ["StreetPrint"] },
  "/images/applications/parking-lots/mission-parking-bays-at-the-building-streetprint-01.jpg": { subject: "Parking bays at the building", place: "Mission", systems: ["StreetPrint"] },
  // parks-paths
  "/images/applications/parks-paths/burnaby-wesburn-park-features-streetbond-01.jpg": { subject: "Wesburn Park features", place: "Burnaby", systems: ["StreetBond"] },
  "/images/applications/parks-paths/burnaby-wesburn-park-spray-arches-streetbond-01.jpg": { subject: "Wesburn Park spray arches", place: "Burnaby", systems: ["StreetBond"] },
  "/images/applications/parks-paths/burnaby-wesburn-park-surface-streetbond-01.jpg": { subject: "Wesburn Park surface", place: "Burnaby", systems: ["StreetBond"] },
  "/images/applications/parks-paths/coquitlam-sheffield-park-from-above-streetbond-01.jpg": { subject: "Sheffield Park from above", place: "Coquitlam", systems: ["StreetBond"] },
  "/images/applications/parks-paths/coquitlam-sheffield-park-path-streetbond-01.jpg": { subject: "Sheffield Park path", place: "Coquitlam", systems: ["StreetBond"] },
  "/images/applications/parks-paths/coquitlam-sheffield-park-structure-streetbond-01.jpg": { subject: "Sheffield Park structure", place: "Coquitlam", systems: ["StreetBond"] },
  "/images/applications/parks-paths/lantzville-village-path-streetprint-01.jpg": { subject: "Village path", place: "Lantzville", systems: ["StreetPrint"] },
  "/images/applications/parks-paths/maple-ridge-park-spray-pad-streetbond-01.jpg": { subject: "Park spray pad", place: "Maple Ridge", systems: ["StreetBond"] },
  "/images/applications/parks-paths/maple-ridge-spray-park-arches-streetbond-01.jpg": { subject: "Spray park arches", place: "Maple Ridge", systems: ["StreetBond"] },
  "/images/applications/parks-paths/maple-ridge-spray-park-surface-streetbond-01.jpg": { subject: "Spray park surface", place: "Maple Ridge", systems: ["StreetBond"] },
  "/images/applications/parks-paths/richmond-alexandra-park-path-streetbond-01.jpg": { subject: "Alexandra Park path", place: "Richmond", systems: ["StreetBond"] },
  "/images/applications/parks-paths/richmond-alexandra-park-path-wide-streetbond-01.jpg": { subject: "Alexandra Park path, wide", place: "Richmond", systems: ["StreetBond"] },
  "/images/applications/parks-paths/surrey-marine-spray-park-detail-streetbond-01.jpg": { subject: "Marine spray park detail", place: "Surrey", systems: ["StreetBond"] },
  "/images/applications/parks-paths/surrey-marine-spray-park-from-above-streetbond-01.jpg": { subject: "Marine spray park from above", place: "Surrey", systems: ["StreetBond"] },
  "/images/applications/parks-paths/surrey-marine-spray-park-streetbond-01.jpg": { subject: "Marine spray park", place: "Surrey", systems: ["StreetBond"] },
  "/images/applications/parks-paths/vancouver-spray-park-surface-streetbond-01.jpg": { subject: "Spray park surface", place: "Vancouver", systems: ["StreetBond"] },
  "/images/applications/parks-paths/vancouver-spray-park-wide-streetbond-01.jpg": { subject: "Spray park, wide", place: "Vancouver", systems: ["StreetBond"] },
  "/images/applications/parks-paths/west-vancouver-spirit-trail-crew-on-site-streetbond-01.jpg": { subject: "Spirit Trail, crew on site", place: "West Vancouver", systems: ["StreetBond"] },
  "/images/applications/parks-paths/west-vancouver-spirit-trail-pattern-streetbond-01.jpg": { subject: "Spirit Trail pattern", place: "West Vancouver", systems: ["StreetBond"] },
  // schools-sports-courts
  "/images/applications/schools-sports-courts/abbotsford-basketball-key-streetbond-01.jpg": { subject: "Basketball key", place: "Abbotsford", systems: ["StreetBond"] },
  "/images/applications/schools-sports-courts/abbotsford-eagle-mountain-labyrinth-crew-on-site-decomark-01.jpg": { subject: "Eagle Mountain labyrinth, crew on site", place: "Abbotsford", systems: ["DecoMark"] },
  "/images/applications/schools-sports-courts/abbotsford-eagle-mountain-labyrinth-decomark-01.jpg": { subject: "Eagle Mountain labyrinth", place: "Abbotsford", systems: ["DecoMark"] },
  "/images/applications/schools-sports-courts/abbotsford-salmon-markings-decomark-01.jpg": { subject: "Salmon markings", place: "Abbotsford", systems: ["DecoMark"] },
  "/images/applications/schools-sports-courts/langford-west-langford-play-shapes-decomark-01.jpg": { subject: "West Langford play shapes", place: "Langford", systems: ["DecoMark"] },
  "/images/applications/schools-sports-courts/langford-west-langford-ramp-decomark-01.jpg": { subject: "West Langford ramp", place: "Langford", systems: ["DecoMark"] },
  "/images/applications/schools-sports-courts/langford-west-langford-target-circles-decomark-01.jpg": { subject: "West Langford target circles", place: "Langford", systems: ["DecoMark"] },
  "/images/applications/schools-sports-courts/lower-mainland-bc-elevated-play-deck-streetbond-01.jpg": { subject: "Elevated play deck", place: "Lower Mainland", systems: ["StreetBond"] },
  "/images/applications/schools-sports-courts/lower-mainland-bc-elevated-play-deck-wide-streetbond-01.jpg": { subject: "Elevated play deck, wide", place: "Lower Mainland", systems: ["StreetBond"] },
  "/images/applications/schools-sports-courts/maple-ridge-park-court-streetbond-01.jpg": { subject: "Park court", place: "Maple Ridge", systems: ["StreetBond"] },
  "/images/applications/schools-sports-courts/maple-ridge-park-courts-from-the-gate-streetbond-01.jpg": { subject: "Park courts from the gate", place: "Maple Ridge", systems: ["StreetBond"] },
  "/images/applications/schools-sports-courts/surrey-kb-woodward-hexagons-decomark-01.jpg": { subject: "KB Woodward hexagons", place: "Surrey", systems: ["DecoMark"] },
  "/images/applications/schools-sports-courts/surrey-kb-woodward-installation-decomark-01.jpg": { subject: "KB Woodward, installation", place: "Surrey", systems: ["DecoMark"] },
  "/images/applications/schools-sports-courts/vancouver-corpus-christi-hopscotch-premark-01.jpg": { subject: "Corpus Christi hopscotch", place: "Vancouver", systems: ["PreMark"] },
  "/images/applications/schools-sports-courts/vancouver-corpus-christi-path-markings-premark-01.jpg": { subject: "Corpus Christi path markings", place: "Vancouver", systems: ["PreMark"] },
  "/images/applications/schools-sports-courts/vancouver-corpus-christi-play-markings-premark-01.jpg": { subject: "Corpus Christi play markings", place: "Vancouver", systems: ["PreMark"] },
  "/images/applications/schools-sports-courts/vancouver-school-court-streetbond-01.jpg": { subject: "School court", place: "Vancouver", systems: ["StreetBond"] },
  "/images/applications/schools-sports-courts/vancouver-school-entrance-play-area-streetbond-01.jpg": { subject: "School entrance play area", place: "Vancouver", systems: ["StreetBond"] },
  "/images/applications/schools-sports-courts/vancouver-school-play-markings-premark-01.jpg": { subject: "School play markings", place: "Vancouver", systems: ["PreMark"] },
  // bike-lanes
  "/images/applications/bike-lanes/sechelt-cowrie-and-trail-intersection-streetbond-01.jpg": { subject: "Cowrie and Trail intersection", place: "Sechelt", systems: ["StreetBond"] },
  "/images/applications/bike-lanes/sechelt-cowrie-and-trail-lane-and-crossing-decomark-01.jpg": { subject: "Cowrie and Trail lane and crossing", place: "Sechelt", systems: ["DecoMark"] },
  "/images/applications/bike-lanes/sechelt-cowrie-and-trail-lane-markings-decomark-01.jpg": { subject: "Cowrie and Trail lane markings", place: "Sechelt", systems: ["DecoMark"] },
  "/images/applications/bike-lanes/surrey-32nd-avenue-bike-path-streetprint-01.jpg": { subject: "32nd Avenue bike path", place: "Surrey", systems: ["StreetPrint"] },
  // public-art
  "/images/applications/public-art/burnaby-union-street-looking-down-the-greenway-decomark-01.jpg": { subject: "Union Street, looking down the greenway", place: "Burnaby", systems: ["DecoMark"] },
  "/images/applications/public-art/burnaby-union-street-thunderbird-decomark-01.jpg": { subject: "Union Street thunderbird", place: "Burnaby", systems: ["DecoMark"] },
  "/images/applications/public-art/colwood-entrance-crossing-streetbond-01.jpg": { subject: "Entrance crossing", place: "Colwood", systems: ["StreetBond"] },
  "/images/applications/public-art/greater-victoria-friendship-centre-walkway-streetbond-01.jpg": { subject: "Friendship Centre walkway", place: "Greater Victoria", systems: ["StreetBond"] },
  "/images/applications/public-art/greater-victoria-friendship-centre-walkway-wide-streetbond-01.jpg": { subject: "Friendship Centre walkway, wide", place: "Greater Victoria", systems: ["StreetBond"] },
  "/images/applications/public-art/langley-events-centre-circle-of-life-decomark-01.jpg": { subject: "Events Centre Circle of Life", place: "Langley", systems: ["DecoMark"] },
  "/images/applications/public-art/langley-events-centre-circle-of-life-wide-decomark-01.jpg": { subject: "Events Centre Circle of Life, wide", place: "Langley", systems: ["DecoMark"] },
  "/images/applications/public-art/new-westminster-agnus-green-from-above-decomark-01.jpg": { subject: "Agnus Green from above", place: "New Westminster", systems: ["DecoMark"] },
  "/images/applications/public-art/new-westminster-agnus-green-medallion-decomark-01.jpg": { subject: "Agnus Green medallion", place: "New Westminster", systems: ["DecoMark"] },
  "/images/applications/public-art/new-westminster-boundary-pump-station-full-field-streetbond-01.jpg": { subject: "Boundary Pump Station, full field", place: "New Westminster", systems: ["StreetBond"] },
  "/images/applications/public-art/new-westminster-boundary-pump-station-plaza-streetbond-01.jpg": { subject: "Boundary Pump Station plaza", place: "New Westminster", systems: ["StreetBond"] },
  "/images/applications/public-art/new-westminster-boundary-pump-station-steps-streetbond-01.jpg": { subject: "Boundary Pump Station steps", place: "New Westminster", systems: ["StreetBond"] },
  "/images/applications/public-art/new-westminster-every-child-matters-installation-decomark-01.jpg": { subject: "Every Child Matters, installation", place: "New Westminster", systems: ["DecoMark"] },
  "/images/applications/public-art/new-westminster-every-child-matters-panel-decomark-01.jpg": { subject: "Every Child Matters panel", place: "New Westminster", systems: ["DecoMark"] },
  "/images/applications/public-art/north-vancouver-lynn-valley-plaza-and-murals-streetbond-01.jpg": { subject: "Lynn Valley plaza and murals", place: "North Vancouver", systems: ["StreetBond"] },
  "/images/applications/public-art/north-vancouver-lynn-valley-plaza-streetbond-01.jpg": { subject: "Lynn Valley plaza", place: "North Vancouver", systems: ["StreetBond"] },
  "/images/applications/public-art/oak-bay-street-mural-crossing-streetbond-01.jpg": { subject: "Street mural crossing", place: "Oak Bay", systems: ["StreetBond"] },
  "/images/applications/public-art/oak-bay-village-intersection-medallion-streetbond-01.jpg": { subject: "Village intersection medallion", place: "Oak Bay", systems: ["StreetBond"] },
  "/images/applications/public-art/oak-bay-village-intersection-wide-streetbond-01.jpg": { subject: "Village intersection, wide", place: "Oak Bay", systems: ["StreetBond"] },
  "/images/applications/public-art/port-coquitlam-commemorative-map-inlay-streetbond-01.jpg": { subject: "Commemorative map inlay", place: "Port Coquitlam", systems: ["StreetBond"] },
  "/images/applications/public-art/sechelt-tsain-ko-from-the-road-decomark-01.jpg": { subject: "Tsain-Ko from the road", place: "Sechelt", systems: ["DecoMark"] },
  "/images/applications/public-art/sechelt-tsain-ko-storefront-medallion-decomark-01.jpg": { subject: "Tsain-Ko storefront medallion", place: "Sechelt", systems: ["DecoMark"] },
  "/images/applications/public-art/vancouver-18th-and-cambie-crossing-streetbond-01.jpg": { subject: "18th and Cambie crossing", place: "Vancouver", systems: ["StreetBond"] },
  "/images/applications/public-art/vancouver-18th-and-cambie-heart-sculpture-streetbond-01.jpg": { subject: "18th and Cambie, heart sculpture", place: "Vancouver", systems: ["StreetBond"] },
  "/images/applications/public-art/vancouver-ackrey-s-alley-laneway-streetbond-01.jpg": { subject: "Ackrey's Alley laneway", place: "Vancouver", systems: ["StreetBond"] },
  "/images/applications/public-art/vancouver-ackrey-s-alley-streetbond-01.jpg": { subject: "Ackrey's Alley", place: "Vancouver", systems: ["StreetBond"] },
  "/images/applications/public-art/victoria-whorl-canoes-medallion-decomark-01.jpg": { subject: "Whorl canoes medallion", place: "Victoria", systems: ["DecoMark"] },
  // branding-wayfinding
  "/images/applications/branding-wayfinding/coquitlam-red-sol-courtyard-decomark-01.jpg": { subject: "Red Sol courtyard", place: "Coquitlam", systems: ["DecoMark"] },
  "/images/applications/branding-wayfinding/coquitlam-red-sol-detail-decomark-01.jpg": { subject: "Red Sol detail", place: "Coquitlam", systems: ["DecoMark"] },
  "/images/applications/branding-wayfinding/coquitlam-retail-plaza-wayfinding-streetbond-01.jpg": { subject: "Retail plaza wayfinding", place: "Coquitlam", systems: ["StreetBond"] },
  "/images/applications/branding-wayfinding/langley-townhome-amenity-markings-premark-01.jpg": { subject: "Townhome amenity markings", place: "Langley", systems: ["PreMark"] },
  "/images/applications/branding-wayfinding/langley-townhome-amenity-path-premark-01.jpg": { subject: "Townhome amenity path", place: "Langley", systems: ["PreMark"] },
  // driveways
  "/images/applications/driveways/lower-mainland-bc-herringbone-driveway-and-walk-streetprint-01.jpg": { subject: "Herringbone driveway and walk", place: "Lower Mainland", systems: ["StreetPrint"] },
  "/images/applications/driveways/maple-ridge-driveway-medallion-streetbond-01.jpg": { subject: "Driveway medallion", place: "Maple Ridge", systems: ["StreetBond"] },
  "/images/applications/driveways/maple-ridge-driveway-recoat-at-dusk-streetbond-01.jpg": { subject: "Driveway recoat at dusk", place: "Maple Ridge", systems: ["StreetBond"] },
  "/images/applications/driveways/maple-ridge-driveway-recoat-with-medallion-streetbond-01.jpg": { subject: "Driveway recoat with medallion", place: "Maple Ridge", systems: ["StreetBond"] },
  "/images/applications/driveways/new-westminster-oxford-laneway-pattern-streetprint-01.jpg": { subject: "Oxford laneway pattern", place: "New Westminster", systems: ["StreetPrint"] },
  "/images/applications/driveways/new-westminster-oxford-strata-laneway-streetprint-01.jpg": { subject: "Oxford strata laneway", place: "New Westminster", systems: ["StreetPrint"] },
  "/images/applications/driveways/new-westminster-oxford-strata-laneway-wet-streetprint-01.jpg": { subject: "Oxford strata laneway, wet", place: "New Westminster", systems: ["StreetPrint"] },
  "/images/applications/driveways/richmond-brick-driveway-streetprint-01.jpg": { subject: "Brick driveway", place: "Richmond", systems: ["StreetPrint"] },
  "/images/applications/driveways/surrey-driveway-recoat-at-the-carport-streetbond-01.jpg": { subject: "Driveway recoat at the carport", place: "Surrey", systems: ["StreetBond"] },
  "/images/applications/driveways/surrey-driveway-recoat-pattern-streetbond-01.jpg": { subject: "Driveway recoat pattern", place: "Surrey", systems: ["StreetBond"] },
  "/images/applications/driveways/surrey-driveway-recoat-streetbond-01.jpg": { subject: "Driveway recoat", place: "Surrey", systems: ["StreetBond"] },
}
